# Generated by Django 2.2.16 on 2020-10-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_load_initial_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="body",
        ),
        migrations.AddField(
            model_name="homepage",
            name="body_yu_yrtes",
            field=models.TextField(blank=True),
        ),
    ]
