# Generated by Django 2.2.16 on 2020-10-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201002_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='abdcd',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hjjhjhkj',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='uriyriw',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
